parent_cfg: configs/waymo_val_121.yaml
source_path: ./data/
exp_name: sensetime_val_2025_04_26_09_21_06_interaction

data:
    selected_frames: [80, 160]
    type: Sensetime

model:
    nsg:
        include_cube_map: False
